module.exports = {
  CATEGORIES: {
    BUILDING: "BUILDING",
    RENOVATION: "RENOVATION"
  },
  STATUSES: {
    ON_MODERATION: "ON_MODERATION",
    ACCEPTED: "ACCEPTED",
    DECLINED: "DECLINED",
    CLOSED: "CLOSED"
  }
};